DROP Database BGA;

CREATE DATABASE BGA;
USE BGA;

CREATE TABLE STUDENT(
	studentId VARCHAR(40) PRIMARY KEY,
	studentName VARCHAR(40) NOT NULL,
    studentBranch VARCHAR(20) NOT NULL,
    studentGender VARCHAR(10) NOT NULL,
    studentPhoneNumber VARCHAR(15) NOT NULL,
	studentEmail VARCHAR(40) NOT NULL,
	studentDOB DATE NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DESC STUDENT;
SELECT * FROM STUDENT;

CREATE TABLE EMPLOYEE(
	employeeId VARCHAR(40) PRIMARY KEY,
	employeeName VARCHAR(40) NOT NULL,
    employeeBranch VARCHAR(20) NOT NULL,
    employeeGender VARCHAR(20) NOT NULL,
    employeePhoneNumber VARCHAR(15) NOT NULL,
	employeeEmail VARCHAR(40) NOT NULL,
	employeeDOB DATE NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DESC EMPLOYEE;
SELECT * FROM EMPLOYEE;

CREATE TABLE EXTERNAL_FRIENDS(
	FId INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	friendName VARCHAR(40) NOT NULL,
    friendPhoneNumber VARCHAR(15) NOT NULL,
	friendEmail VARCHAR(40) NOT NULL,
    friendMailSubject VARCHAR(40) NOT NULL,
    friendMailMessage VARCHAR(80) NOT NULL,
    friendRefereeName VARCHAR(40) NOT NULL,
	friendRefereeEmail VARCHAR(40) NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY duplicateGreetings (friendEmail,friendRefereeEmail)
);
DESC EXTERNAL_FRIENDS;
SELECT * FROM EXTERNAL_FRIENDS;